name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Install dependencies (Terragrunt)
      - name: Install Terragrunt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.32.3/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      # Debug environment variables for transparency
      - name: Debug Environment Variables
        run: env | sort

      # Initialize Terragrunt
      - name: Initialize Terragrunt
        run: terragrunt init

      # Plan Infrastructure
      - name: Plan Infrastructure
        run: terragrunt plan

      # Apply Infrastructure
      - name: Apply Infrastructure
        run: terragrunt apply -auto-approve

      # DockerHub Login
      - name: DockerHub Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/demo-app" .
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/demo-app"

    # Set environment variables
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
