# path: Leumi-Jenkins-Pipeline/helm-values.yaml

# Docker image - dynamically populated based on ECR repo and version
image:
  repository: "{{ .Values.global.ecr_repo }}/python-app"  # ECR repo dynamically passed from Terraform
  tag: "{{ .Values.image.tag }}"                         # Tag dynamically fetched or provided via Terraform

# Service details for the Python app
service:
  type: "{{ .Values.global.service_type }}"  # ClusterIP, LoadBalancer, or NodePort - dynamic input
  port: {{ .Values.service.port }}           # Dynamic service port, passed from Terraform

# Ingress settings for external access
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: "{{ .Values.global.domain_name }}"  # Dynamically passed domain name from Terraform
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: "{{ .Values.global.tls_secret_name }}"  # Dynamic TLS secret for HTTPS
      hosts:
        - "{{ .Values.global.domain_name }}"              # Same domain used for HTTPS
