apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::864492617736:role/dvorkinguy-leumi-jenkins-eks-control-plane
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:masters
    - rolearn: arn:aws:iam::864492617736:role/dvorkinguy-leumi-jenkins-eks-worker-node
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::864492617736:role/EKS_Cluster_Access
      username: cluster-access
      groups:
        - system:masters
    - rolearn: arn:aws:iam::864492617736:role/leumi-jenkins-dev-eks-cluster-cluster-role
      username: cluster-access
      groups:
        - system:masters
